"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def problem(lim):
    result = 0
    fib_even_1 = 2
    fib_even_2 = 8

    while fib_even_1 <= lim:
        result += fib_even_1
        fib_even_1, fib_even_2 = fib_even_2, 4 * fib_even_2 + fib_even_1
    return result


if __name__ == '__main__':
    print('Answer:', problem(4 * 10 ** 6))
