"""
Pentagon numbers
Problem 44 
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, 
is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
and D = |Pk − Pj| is minimised; what is the value of D?
"""


def problem():
    pentagon_nums = {}
    n, pentagon_num = 1, 0
    break_flag = False
    while not break_flag:
        pentagon_num += 3 * n - 2  # == Pn
        pentagon_nums[pentagon_num] = n
        m, right = n, pentagon_num
        while right > pentagon_num // 2:
            right -= 3 * m - 2
            m -= 1
            diff = 2 * right - pentagon_num
            if (diff in pentagon_nums) and ((right - diff) in pentagon_nums):
                left = right - diff
                i_left, i_right = pentagon_nums[left], pentagon_nums[right]
                i_diff = pentagon_nums[diff]
                print('P{} + P{} = {} + {} = {} = P{}'.
                      format(i_right, i_left, right, left, pentagon_num, n))
                print('P{} - P{} = {} - {} = {} = P{}'.
                      format(i_right, i_left, right, left, diff, i_diff))
                break_flag = True
                break
        n += 1
    return diff


if __name__ == '__main__':
    print('Answer:', problem())
