"""
Pentagon numbers
Problem 44 
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, 
is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
and D = |Pk − Pj| is minimised; what is the value of D?
"""

#
# def pentagon_num(x):
#     return x * (3 * x - 1) // 2

from time import time

st = time()
pentagon_nums = {}
n, pentagon_num = 1, 0
flag = False
while True:
    pentagon_num += 3 * n - 2  # == Pn
    pentagon_nums[pentagon_num] = n
    m, right = n, pentagon_num
    while right > pentagon_num // 2:
        right -= 3 * m - 2
        m -= 1
        diff = 2 * right - pentagon_num
        if (diff in pentagon_nums) and ((right - diff) in pentagon_nums):
            left = right - diff
            print('P{} + P{} = {} + {} = {} = P{}'.format(pentagon_nums[left], pentagon_nums[right], left, right, pentagon_num, n))
            print('P{} - P{} = {} - {} = {} = P{}'.format(pentagon_nums[right], pentagon_nums[left], right, left, diff, pentagon_nums[diff]))
            flag = True
    n += 1
    if flag:
        break

print(time() - st)
